#!/usr/bin/python3
__copyright__ = '''
    Copyright 2022 F4E | European Joint Undertaking for ITER and
    the Development of Fusion Energy ('Fusion for Energy').
    Licensed under the EUPL, Version 1.1 or - as soon they will be approved
    by the European Commission - subsequent versions of the EUPL (the "Licence")
    You may not use this work except in compliance with the Licence.
    You may obtain a copy of the Licence at: http://ec.europa.eu/idabc/eupl

    Unless required by applicable law or agreed to in writing,
    software distributed under the Licence is distributed on an "AS IS"
    basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
    or implied. See the Licence permissions and limitations under the Licence.
'''
__license__ = 'EUPL'
__author__ = 'Andre Neto'
__date__ = '12/04/2026'

###
# Imports
###
import copy
import logging
import os
import re

from marte2_manager.core.base_manager import BaseManager
from pathlib import Path
from string import Template

###
# Globals
###
logger = logging.getLogger(__name__)

###
# Classes
###

class ComponentManager(BaseManager):

    TAB = '    '

    """
    Manage the creation of components.
    """
    def __init__(self, app_def_data, resources_files, template_global_vars, project_name=None, project_path=None):
        super().__init__(app_def_data, resources_files, template_global_vars, project_name, project_path)

    def create_component(self, comp_type, comp_name, comp_namespace):
        """
        Create a new component of the given type.
        """
        self._comp_type = comp_type
        self._comp_name = comp_name
        self._comp_namespace = comp_namespace
        ok = self._add_component_folders()
        if ok:
            ok = self._add_makefiles()
        if ok:
            ok = self._patch_parent_makefiles()
        if ok:
            ok = self._add_component_files()
        if ok:
            ok = self._patch_startup_marte_app_sh()
        return ok

    def expand_from_template(self, template_dict):
        src_folder_name = self._app_def_data['folders']['src']['name']
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        header_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.h'
        header_lines = []
        for parameter_name in template_dict['parameters']:
            parameter = template_dict['parameters'][parameter_name]
            header_lines.append(self._expand_parameter_info_header(parameter_name, parameter))
        ok = self._replace_autogenerated_section(header_file_path, header_lines, '///AUTO-GENERATED: PARAMETERS. DO NOT EDIT!', '///AUTO-GENERATED: END OF PARAMETERS. DO NOT EDIT!')

        src_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.cpp'
        autogenerated_start_markers = [
            '///AUTO-GENERATED: CTOR PARAMETERS. DO NOT EDIT!',
            '///AUTO-GENERATED: DTOR PARAMETERS. DO NOT EDIT!',
            '///AUTO-GENERATED: INITIALISE PARAMETERS. DO NOT EDIT!']
        autogenerated_end_markers = [
            '///AUTO-GENERATED: END OF CTOR PARAMETERS. DO NOT EDIT!',
            '///AUTO-GENERATED: END OF DTOR PARAMETERS. DO NOT EDIT!',
            '///AUTO-GENERATED: END OF INITIALISE PARAMETERS. DO NOT EDIT!']
        expand_functions = [
            self._expand_parameter_info_constructor,
            self._expand_parameter_info_destructor,
            self._expand_parameter_info_initialise]
        for autogenerated_start_marker, autogenerated_end_marker, expand_function in zip(autogenerated_start_markers, autogenerated_end_markers, expand_functions):
            if not ok:
                break
            lines = []
            for parameter_name in template_dict['parameters']:
                parameter = template_dict['parameters'][parameter_name]
                lines.append(expand_function(parameter_name, parameter))
            lines += ['\n']
            ok = self._replace_autogenerated_section(src_file_path, lines, autogenerated_start_marker, autogenerated_end_marker)

        return ok
    
    def expand_gam_signals_from_template(self, template_dict):
        src_folder_name = self._app_def_data['folders']['src']['name']
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        header_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.h'
        header_lines = []
        for signal_io in ['input_signals', 'output_signals']:
            for signal_name in template_dict[signal_io]:
                signal = template_dict[signal_io][signal_name]
                header_lines.append(self._expand_gam_signal_info_header(signal_name, signal))
        ok = self._replace_autogenerated_section(header_file_path, header_lines, '///AUTO-GENERATED: SIGNALS. DO NOT EDIT!', '///AUTO-GENERATED: END OF SIGNALS. DO NOT EDIT!')

        src_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.cpp'
        autogenerated_start_markers = [
            '///AUTO-GENERATED: CTOR SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: SETUP SIGNALS. DO NOT EDIT!']
        autogenerated_end_markers = [
            '///AUTO-GENERATED: END OF CTOR SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: END OF SETUP SIGNALS. DO NOT EDIT!']
        expand_functions_pre = [
            None,
            self._expand_gam_signal_info_setup_pre
        ]
        expand_functions = [
            self._expand_gam_signal_info_constructor,
            self._expand_gam_signal_info_setup]
        for autogenerated_start_marker, autogenerated_end_marker, expand_function_pre, expand_function  in zip(autogenerated_start_markers, autogenerated_end_markers, expand_functions_pre, expand_functions):
            if not ok:
                break
            lines = []
            signal_direction = {'input_signals': 'InputSignals', 'output_signals': 'OutputSignals'}
            for signal_io in ['input_signals', 'output_signals']:
                if expand_function_pre is not None:
                    lines.append(expand_function_pre(template_dict[signal_io], signal_io))
                for idx, signal_name in enumerate(template_dict[signal_io]):
                    signal = template_dict[signal_io][signal_name]
                    lines.append(expand_function(signal_name, signal, signal_direction[signal_io], idx))
            lines += ['\n']
            ok = self._replace_autogenerated_section(src_file_path, lines, autogenerated_start_marker, autogenerated_end_marker)
        return ok

    def expand_datasource_signals_from_template(self, template_dict):
        src_folder_name = self._app_def_data['folders']['src']['name']
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        header_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.h'
        header_lines = []
        for signal_name in template_dict['signals']:
            signal = template_dict['signals'][signal_name]
            header_lines.append(self._expand_datasource_signal_info_header(signal_name, signal))
        ok = self._replace_autogenerated_section(header_file_path, header_lines, '///AUTO-GENERATED: SIGNALS. DO NOT EDIT!', '///AUTO-GENERATED: END OF SIGNALS. DO NOT EDIT!')

        src_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.cpp'
        autogenerated_start_markers = [
            '///AUTO-GENERATED: CTOR SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: DTOR SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: SETUP SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: GET MEMORY SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: ALLOCATE MEMORY SIGNALS. DO NOT EDIT!']
        autogenerated_end_markers = [
            '///AUTO-GENERATED: END OF CTOR SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: END OF DTOR SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: END OF SETUP SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: END OF GET MEMORY SIGNALS. DO NOT EDIT!',
            '///AUTO-GENERATED: END OF ALLOCATE MEMORY SIGNALS. DO NOT EDIT!']
        expand_functions_pre = [
            None,
            None,
            self._expand_datasource_signal_info_setup_pre,
            None,
            None
        ]
        expand_functions = [
            self._expand_datasource_signal_info_constructor,
            self._expand_datasource_signal_info_destructor,
            self._expand_datasource_signal_info_setup,
            self._expand_datasource_signal_info_get_memory,
            self._expand_datasource_signal_info_allocate_memory]

        for autogenerated_start_marker, autogenerated_end_marker, expand_function_pre, expand_function in zip(autogenerated_start_markers, autogenerated_end_markers, expand_functions_pre, expand_functions):
            if not ok:
                break
            lines = []
            if expand_function_pre is not None:
                lines.append(expand_function_pre(template_dict['signals']))  
            for idx, signal_name in enumerate(template_dict['signals']):
                signal = template_dict['signals'][signal_name]
                lines.append(expand_function(signal_name, signal, idx))
            lines += ['\n']
            ok = self._replace_autogenerated_section(src_file_path, lines, autogenerated_start_marker, autogenerated_end_marker)

        if ok:
            lines = []
            datasource_dir = template_dict['direction']
            if datasource_dir == 'input':
                lines.append(f'{self.TAB}brokerName = "MemoryMapSynchronisedInputBroker";\n')
            else:
                lines.append(f'{self.TAB}brokerName = "MemoryMapSynchronisedOutputBroker";\n')
            ok = self._replace_autogenerated_section(src_file_path, lines, '///AUTO-GENERATED: GET BROKER NAME. DO NOT EDIT!', '///AUTO-GENERATED: END OF GET BROKER NAME. DO NOT EDIT!') 
        return ok

    def validate_component(self, comp_type, comp_name):
        self._comp_type = comp_type
        self._comp_name = comp_name
        src_folder_name = self._app_def_data['folders']['src']['name']
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']

        src_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.cpp'
        ok = os.path.exists(src_file_path)
        if not ok:
            logger.critical(f'Component source file not found: {src_file_path}')
        if ok:
            header_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.h'
            ok = os.path.exists(header_file_path)
            if not ok:
                logger.critical(f'Component header file not found: {header_file_path}')

        return ok

    def generate_gam_doc_from_template(self, template_dict):
        doc_lines = []
        doc_lines.append(self._expand_doc_header(template_dict))

        src_folder_name = self._app_def_data['folders']['src']['name']
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        header_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.h'

        for parameter_name in template_dict['parameters']:
            parameter = template_dict['parameters'][parameter_name]
            doc_lines.append(self._expand_parameter_info_header_doc(parameter_name, parameter))


        signal_io_map = {'input_signals': 'InputSignals', 'output_signals': 'OutputSignals'}
        for signal_io in ['input_signals', 'output_signals']:

            if len(template_dict[signal_io]) > 0:
                doc_lines.append(f'\n * {self.TAB}{signal_io_map[signal_io]} = {{')
                for signal_name in template_dict[signal_io]:
                    signal = template_dict[signal_io][signal_name]
                    doc_lines.append(self._expand_gam_signal_info_header_doc(signal_name, signal))
            doc_lines.append(f'\n * {self.TAB}}}')

        doc_lines.append(f'\n * }}')
        doc_lines.append('\n */\n')
        ok = self._replace_autogenerated_section(header_file_path, doc_lines, '///AUTO-GENERATED: CLASS DOC. DO NOT EDIT!', '///AUTO-GENERATED: END OF CLASS DOC. DO NOT EDIT!')
        return ok

    def generate_datasource_doc_from_template(self, template_dict):
        doc_lines = []
        doc_lines.append(self._expand_doc_header(template_dict))

        src_folder_name = self._app_def_data['folders']['src']['name']
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        header_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.h'

        for parameter_name in template_dict['parameters']:
            parameter = template_dict['parameters'][parameter_name]
            doc_lines.append(self._expand_parameter_info_header_doc(parameter_name, parameter))

        if len(template_dict['signals']) > 0:
            doc_lines.append(f'\n * {self.TAB}Signals = {{')
            for signal_name in template_dict['signals']:
                signal = template_dict['signals'][signal_name]
                doc_lines.append(self._expand_datasource_signal_info_header_doc(signal_name, signal))
        doc_lines.append(f'\n * {self.TAB}}}')

        doc_lines.append(f'\n * }}')
        doc_lines.append('\n */\n')
        ok = self._replace_autogenerated_section(header_file_path, doc_lines, '///AUTO-GENERATED: CLASS DOC. DO NOT EDIT!', '///AUTO-GENERATED: END OF CLASS DOC. DO NOT EDIT!')
        return ok


    def print_component_configuration(self, template_dict):
        ok = True
        doc_lines = []

        doc_lines.append(f'\n+{self._comp_name}Instance = {{')
        doc_lines.append(f'\n{self.TAB}Class = {self._comp_name}')
        src_folder_name = self._app_def_data['folders']['src']['name']
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        header_file_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name / f'{self._comp_name}.h'

        for parameter_name in template_dict['parameters']:
            parameter = template_dict['parameters'][parameter_name]
            doc_lines.append(self._expand_parameter_info_header_doc(parameter_name, parameter, prefix='', expand_description=False))

        if self._comp_type == 'gams':
            signal_io_map = {'input_signals': 'InputSignals', 'output_signals': 'OutputSignals'}
            for signal_io in ['input_signals', 'output_signals']:
                if len(template_dict[signal_io]) > 0:
                    doc_lines.append(f'\n{self.TAB}{signal_io_map[signal_io]} = {{')
                    for signal_name in template_dict[signal_io]:
                        signal = template_dict[signal_io][signal_name]
                        doc_lines.append(self._expand_gam_signal_info_header_doc(signal_name, signal, prefix='', expand_description=False))
                doc_lines.append(f'\n{self.TAB}}}')
        elif self._comp_type == 'datasources':
            if len(template_dict['signals']) > 0:
                doc_lines.append(f'\n{self.TAB}Signals = {{')
                for signal_name in template_dict['signals']:
                    signal = template_dict['signals'][signal_name]
                    doc_lines.append(self._expand_datasource_signal_info_header_doc(signal_name, signal, prefix='', expand_description=False))
                doc_lines.append(f'\n{self.TAB}}}')

        doc_lines.append(f'\n}}')
        print(''.join(doc_lines))
        return ok

    def _expand_doc_header(self, template_dict):
        lines = '/**'
        lines += f'\n * @details'
        lines += f'\n * +{self._comp_name}Instance = {{'
        lines += f'\n * {self.TAB}Class = {self._comp_name}'
        return lines

    def _expand_parameter_info_header_doc(self, parameter_name, parameter_info, prefix = ' * ', expand_description = True):
        default_value = parameter_info.get('default_value', None)
        parameter_type = parameter_info['type']
        if parameter_type == 'enum':
            enum_0_val = list(parameter_info['enum_values'].keys())[0]
            default_value = f'"{enum_0_val}"'

        if default_value is None:
            if parameter_type == 'StreamString':
                default_value = '""'
            else:
                default_value = '0' 

        number_of_elements = parameter_info.get('number_of_elements', 1) 
        if isinstance(number_of_elements, int):
            if number_of_elements > 1:
                if parameter_type == 'StreamString':
                    default_value = '{' + ' '.join(['" "'] * number_of_elements) + '}'
                else:
                    default_value = '{' + ' '.join(['0'] * number_of_elements) + '}'
        elif isinstance(number_of_elements, list):
            number_of_rows = number_of_elements[0]
            number_of_cols = number_of_elements[1]
            default_value = '{'
            for r in range(number_of_rows):
                default_value += '{' + ' '.join(['0'] * number_of_cols) + '}'
            default_value += '}'

        required_parameter = parameter_info.get('required', False)
        line  = f'\n{prefix}{self.TAB}{parameter_name} = {default_value}'
        if expand_description:
            line += ' //'
            if required_parameter:
                line += 'Required. '
            else:
                line += 'Optional. '

            if parameter_type == 'enum':
                line += f'Options: {", ".join(parameter_info["enum_values"].keys())}. '

            line += f'{parameter_info["description"]}'
        return line


    def _expand_parameter_info_header(self, parameter_name, parameter_info):
        description = parameter_info['description']
        parameter_type = parameter_info['type']
        if parameter_type == 'enum':
            parameter_type = parameter_info.get('enum_type', 'uint32')
        if not parameter_type.startswith('MARTe::'):
            parameter_type = f'MARTe::{parameter_type}'

        number_of_elements = parameter_info.get('number_of_elements', 1)
        
        if isinstance(number_of_elements, int):
            if number_of_elements > 1:
                parameter_type += ' *' 
            else:
                parameter_type += ' '
        elif isinstance(number_of_elements, list):
            parameter_type += ' **' 
        else:
            parameter_type += ' '
            logger.warning(f'Parameter {parameter_name} has an invalid number_of_elements: {number_of_elements}. Defaulting to 1.')

        parameter_name_lower_case = self._generate_lower_case_var(parameter_name)
        line  = f'\n{self.TAB}/**'
        line += f'\n{self.TAB} * {description}'
        line += f'\n{self.TAB} */'
        line += f'\n{self.TAB}{parameter_type}{parameter_name_lower_case};'
        line += '\n'

        if isinstance(number_of_elements, int):
            if number_of_elements > 1:
                line += f'{self.TAB}MARTe::uint32 nOfElements{parameter_name};'
        elif isinstance(number_of_elements, list):
            line += f'{self.TAB}MARTe::uint32 nOfRows{parameter_name};'
            line += f'\n{self.TAB}MARTe::uint32 nOfCols{parameter_name};\n'

        return line

    def _expand_gam_signal_info_header(self, signal_name, signal_info):
        description = signal_info['description']
        signal_type = signal_info['type']
        if not signal_type.startswith('MARTe::'):
            signal_type = f'MARTe::{signal_type}'

        number_of_elements = signal_info.get('number_of_elements', 1)
        number_of_samples = signal_info.get('samples', 1)

        signal_name_lower_case = self._generate_lower_case_var(signal_name) 
        line  = f'\n{self.TAB}/**'
        line += f'\n{self.TAB} * {description}'
        line += f'\n{self.TAB} */'
        line += f'\n{self.TAB}{signal_type} *{signal_name_lower_case};'

        if number_of_elements > 1:
            line += f'\n{self.TAB}MARTe::uint32 nOfElements{signal_name};'

        if number_of_samples > 1:
            line += f'\n{self.TAB}MARTe::uint32 nOfSamples{signal_name};'

        line += '\n'

        return line

    def _expand_datasource_signal_info_header(self, signal_name, signal_info):
        description = signal_info['description']
        signal_type = signal_info['type']
        if not signal_type.startswith('MARTe::'):
            signal_type = f'MARTe::{signal_type}'

        number_of_elements = signal_info.get('number_of_elements', 1)

        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        line  = f'\n{self.TAB}/**'
        line += f'\n{self.TAB} * {description}'
        line += f'\n{self.TAB} */'

        if number_of_elements > 1:
            line += f'\n{self.TAB}{signal_type} *{signal_name_lower_case};'
            line += f'\n{self.TAB}MARTe::uint32 nOfElements{signal_name};'
        else:
            line += f'\n{self.TAB}{signal_type} {signal_name_lower_case};'

        line += '\n'

        return line

    def _expand_gam_signal_info_header_doc(self, signal_name, signal_info, prefix = ' * ', expand_description = True):
        description = signal_info['description']
        signal_type = signal_info['type']
        number_of_elements = signal_info.get('number_of_elements', 1)
        number_of_samples = signal_info.get('samples', 1)
        line  = f'\n{prefix}{self.TAB}{self.TAB}{signal_name} = {{'
        if expand_description:
            line += f'//{description}'
        line  += f'\n{prefix}{self.TAB}{self.TAB}{self.TAB}Type = {signal_type}'
        if number_of_elements > 1:
            line  += f'\n{prefix}{self.TAB}{self.TAB}{self.TAB}NumberOfElements = {number_of_elements}'
        if number_of_samples > 1:
            line  += f'\n{prefix}{self.TAB}{self.TAB}{self.TAB}Samples = {number_of_samples}'
        line  += f'\n{prefix}{self.TAB}{self.TAB}{self.TAB}DataSource = "DDB1"'

        line += f'\n{prefix}{self.TAB}{self.TAB}}}'

        return line

    def _expand_datasource_signal_info_header_doc(self, signal_name, signal_info, prefix = ' * ', expand_description = True):
        description = signal_info['description']
        signal_type = signal_info['type']
        number_of_elements = signal_info.get('number_of_elements', 1)
        line  = f'\n{prefix}{self.TAB}{self.TAB}{signal_name} = {{'
        if expand_description:
            line += f'//{description}'
        line  += f'\n{prefix}{self.TAB}{self.TAB}{self.TAB}Type = {signal_type}'
        if number_of_elements > 1:
            line  += f'\n{prefix}{self.TAB}{self.TAB}{self.TAB}NumberOfElements = {number_of_elements}'
        line += f'\n{prefix}{self.TAB}{self.TAB}}}'

        return line

    def _expand_parameter_info_constructor(self, parameter_name, parameter_info):
        parameter_name_lower_case = self._generate_lower_case_var(parameter_name)
        parameter_type = parameter_info['type']
        if parameter_type == 'enum':
            parameter_type = parameter_info.get('enum_type', 'uint32')

        line = f'\n{self.TAB}{parameter_name_lower_case}'

        number_of_elements = parameter_info.get('number_of_elements', 1)
        if isinstance(number_of_elements, int):
            if number_of_elements > 1:
                line += f' = NULL_PTR({parameter_type} *);'
            else:
                if 'int' in parameter_type:
                    line += ' = 0;'
                elif 'float' in parameter_type:
                    line += ' = 0.0f;'
                elif 'bool' in parameter_type:
                    line += ' = false;'
                else:                     
                    line += ' = "";'
        elif isinstance(number_of_elements, list):
            line += f' = NULL_PTR({parameter_type} **);'
        else:
            line += ' = 0;'
        
        if isinstance(number_of_elements, int):
            if number_of_elements > 1:
                line += f'\n{self.TAB}nOfElements{parameter_name} = 0;'
        elif isinstance(number_of_elements, list):
            line += f'\n{self.TAB}nOfRows{parameter_name} = 0;'
            line += f'\n{self.TAB}nOfCols{parameter_name} = 0;'

        return line 

    def _expand_parameter_info_destructor(self, parameter_name, parameter_info):
        line = ''
        parameter_name_lower_case = self._generate_lower_case_var(parameter_name)
        parameter_type = parameter_info['type']
        if parameter_type == 'enum':
            parameter_type = 'uint32'
        number_of_elements = parameter_info.get('number_of_elements', 1)
        if isinstance(number_of_elements, int):
            if number_of_elements > 1:
                line = f'\n{self.TAB}if ({parameter_name_lower_case} != NULL_PTR({parameter_type} *)) {{'
                line += f'\n{self.TAB}{self.TAB}delete[] {parameter_name_lower_case};'
                line += f'\n{self.TAB}}}'
        elif isinstance(number_of_elements, list):
            line = f'\n{self.TAB}if ({parameter_name_lower_case} != NULL_PTR({parameter_type} **)) {{'
            line += f'\n{self.TAB}{self.TAB}for (MARTe::uint32 i = 0; i < nOfRows{parameter_name}; i++) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}if ({parameter_name_lower_case}[i] != NULL_PTR({parameter_type} *)) {{'  
            line += f'\n{self.TAB}{self.TAB}{self.TAB}{self.TAB}delete[] {parameter_name_lower_case}[i];'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}delete[] {parameter_name_lower_case};'
            line += f'\n{self.TAB}}}'

        return line

    def _expand_parameter_info_initialise(self, parameter_name, parameter_info):
        line = f'\n{self.TAB}if (ok) {{'
        parameter_type = parameter_info.get('enum_type', 'uint32')
        is_enum = parameter_type == 'enum'
        number_of_elements = parameter_info.get('number_of_elements', 1)
        if isinstance(number_of_elements, int):
            if number_of_elements > 1:
                line += self._expand_init_array(parameter_name, parameter_info) 
            else:
                if is_enum:
                    line += self._expand_init_enum(parameter_name, parameter_info)
                else:
                    line += self._expand_init_scalar(parameter_name, parameter_info)                    
        elif isinstance(number_of_elements, list):
            line += self._expand_init_matrix(parameter_name, parameter_info)

        line += f'\n{self.TAB}}}'
        return line

    def _expand_init_enum(self, parameter_name, parameter_info):
        default_value = parameter_info.get('default_value', None)
        parameter_type = parameter_info.get('enum_type', 'uint32')
        parameter_name_lower_case = self._generate_lower_case_var(parameter_name)
        line = f'\n{self.TAB}{self.TAB}const char8 *enum{parameter_name}Strings[] = {{'
        for enum_name in parameter_info['enum_values']:
            line += f'"{enum_name}",'
        line = line[:-1] # Remove the last comma
        line += '};'
        line += f'\n{self.TAB}{self.TAB}{parameter_type} enum{parameter_name}Values[] = {{'
        for enum_name in parameter_info['enum_values']:
            enum_value = parameter_info['enum_values'][enum_name]
            line += f'{enum_value},'
        line = line[:-1] # Remove the last comma
        line += '};'
        if default_value is None:
            line += f'\n{self.TAB}{self.TAB}ok = helper.ReadEnum("{parameter_name}", {parameter_name_lower_case}, enum{parameter_name}Strings, enum{parameter_name}Values);'
        else:
            line += f'\n{self.TAB}{self.TAB}ok = helper.ReadEnum("{parameter_name}", {parameter_name_lower_case}, enum{parameter_name}Strings, enum{parameter_name}Values, {default_value});'

        return line

    def _expand_init_scalar(self, parameter_name, parameter_info):
        parameter_name_lower_case = self._generate_lower_case_var(parameter_name)
        parameter_type = parameter_info['type']
        default_value = parameter_info.get('default_value', None)
        validation = parameter_info.get('validation', None)
        if validation is not None:
            line = f'\n{self.TAB}{self.TAB}ok = helper.ReadValidated("{parameter_name}", {parameter_name_lower_case}, "{validation}");'
        elif default_value is not None:
            if parameter_type == 'StreamString':
                default_value = f'"{default_value}"'
            line = f'\n{self.TAB}{self.TAB}ok = helper.Read("{parameter_name}", {parameter_name_lower_case}, {default_value});'
        else:
            line = f'\n{self.TAB}{self.TAB}ok = helper.Read("{parameter_name}", {parameter_name_lower_case});'
        return line

    def _expand_init_array(self, parameter_name, parameter_info):
        parameter_name_lower_case = self._generate_lower_case_var(parameter_name)
        line = f'\n{self.TAB}{self.TAB}ok = helper.ReadArray("{parameter_name}", {parameter_name_lower_case}, nOfElements{parameter_name});'
        number_of_elements_fixed = parameter_info.get('number_of_elements_fixed', False)
        if number_of_elements_fixed:
            number_of_elements = parameter_info.get('number_of_elements', 1)
            line = f'\n{self.TAB}{self.TAB}if (ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}ok = (nOfElements{parameter_name} == {number_of_elements});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}if (!ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Expected %d elements and read %d", {number_of_elements}, nOfElements{parameter_name});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}}}'
        return line

    def _expand_init_matrix(self, parameter_name, parameter_info):
        parameter_name_lower_case = self._generate_lower_case_var(parameter_name)
        line = f'\n{self.TAB}{self.TAB}ok = helper.ReadMatrix("{parameter_name}", {parameter_name_lower_case}, nOfRows{parameter_name}, nOfCols{parameter_name});'
        number_of_elements_fixed = parameter_info.get('number_of_elements_fixed', False)
        if number_of_elements_fixed:
            number_of_elements = parameter_info.get('number_of_elements', [1, 1])
            number_of_rows = number_of_elements[0]
            number_of_cols = number_of_elements[1]
            line = f'\n{self.TAB}{self.TAB}if (ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}ok = (nOfRows{parameter_name} == {number_of_rows});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}if (!ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Expected %d rows and read %d", {number_of_rows}, nOfRows{parameter_name});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}if (ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}ok = (nOfCols{parameter_name} == {number_of_cols});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}if (!ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Expected %d cols and read %d", {number_of_cols}, nOfCols{parameter_name});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}}}'
        return line

    def _expand_gam_signal_info_constructor(self, signal_name, signal_info, signal_direction, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        signal_type = signal_info['type']

        line = f'\n{self.TAB}{signal_name_lower_case} = NULL_PTR({signal_type} *);'
        number_of_elements = signal_info.get('number_of_elements', 1)
        if number_of_elements > 1:
            line += f'\n{self.TAB}nOfElements{signal_name} = 0;'

        number_of_samples = signal_info.get('samples', 1)
        if number_of_samples > 1:
            line += f'\n{self.TAB}nOfSamples{signal_name} = 0;'

        return line

    def _expand_datasource_signal_info_constructor(self, signal_name, signal_info, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        signal_type = signal_info['type']

        number_of_elements = signal_info.get('number_of_elements', 1)
        if number_of_elements > 1:
            line = f'\n{self.TAB}{signal_name_lower_case} = NULL_PTR({signal_type} *);'
            line += f'\n{self.TAB}nOfElements{signal_name} = 0;'
        else:
            line = f'\n{self.TAB}{signal_name_lower_case} = 0;'

        return line

    def _expand_datasource_signal_info_destructor(self, signal_name, signal_info, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        signal_type = signal_info['type']

        number_of_elements = signal_info.get('number_of_elements', 1)
        line = ''
        if number_of_elements > 1:
            line = f'\n{self.TAB}if ({signal_name_lower_case} != NULL_PTR({signal_type} *)) {{'
            line += f'\n{self.TAB}{self.TAB}delete[] {signal_name_lower_case};'
            line += f'\n{self.TAB}}}'
        return line

    def _expand_datasource_signal_info_get_memory(self, signal_name, signal_info, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        signal_type = signal_info['type']

        number_of_elements = signal_info.get('number_of_elements', 1)
        if idx == 0:
            line = f'\n{self.TAB}if (signalIdx == 0) {{'
        else:
            line = f'\n{self.TAB}else if (signalIdx == {idx}) {{'
        line += f'\n{self.TAB}{self.TAB}signalAddress = '
        if number_of_elements > 1:
            line += f'&{signal_name_lower_case}[0];'
        else:
            line += f'&{signal_name_lower_case};'
        line += f'\n{self.TAB}}}'

        return line

    def _expand_datasource_signal_info_allocate_memory(self, signal_name, signal_info, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        signal_type = signal_info['type']
        line = ''
        number_of_elements = signal_info.get('number_of_elements', 1)
        if number_of_elements > 1:
            line = f'\n{self.TAB}{signal_name_lower_case} = new {signal_type}[{number_of_elements}];'

        return line

    def _expand_gam_signal_info_setup(self, signal_name, signal_info, signal_direction, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        line = f'\n{self.TAB}if (ok) {{'
        line += self._expand_gam_setup_signal_type(signal_name, signal_info, signal_direction, idx)
        line += f'\n{self.TAB}}}'
        number_of_elements_fixed = signal_info.get('number_of_elements_fixed', True)
        number_of_elements = signal_info.get('number_of_elements', 1)
        if number_of_elements > 1 or not number_of_elements_fixed:
            line += f'\n{self.TAB}if (ok) {{'
            line += self._expand_gam_setup_signal_n_elements(signal_name, signal_info, signal_direction, number_of_elements, idx)
            line += f'\n{self.TAB}}}'
        number_of_samples_fixed = signal_info.get('number_of_samples_fixed', True)
        number_of_samples = signal_info.get('samples', 1)
        if number_of_samples > 1 or not number_of_samples_fixed:
            line += f'\n{self.TAB}if (ok) {{'
            line += self._expand_gam_setup_signal_samples(signal_name, signal_info, signal_direction, number_of_samples_fixed, idx)
            line += f'\n{self.TAB}}}'
        line += f'\n{self.TAB}if (ok) {{'
        line += self._expand_gam_setup_signal_memory(signal_name, signal_info, signal_direction, number_of_samples_fixed, idx)
        line += f'\n{self.TAB}}}'
        return line

    def _expand_gam_signal_info_setup_pre(self, signals, signal_direction):
        line = f'\n{self.TAB}if (ok) {{'
        if signal_direction == 'input_signals':
            line += f'\n{self.TAB}{self.TAB}ok = (GetNumberOfInputSignals() == ' + str(len(signals)) + ');'
            line += f'\n{self.TAB}{self.TAB}if (!ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Unexpected number of input signals. Expected {0} and read %d", ' + str(len(signals)) + ', GetNumberOfInputSignals());'
            line += f'\n{self.TAB}{self.TAB}}}'
        else:
            line += f'\n{self.TAB}{self.TAB}ok = (GetNumberOfOutputSignals() == ' + str(len(signals)) + ');'
            line += f'\n{self.TAB}{self.TAB}if (!ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Unexpected number of output signals. Expected {0} and read %d", ' + str(len(signals)) + ', GetNumberOfOutputSignals());'
            line += f'\n{self.TAB}{self.TAB}}}'
        line += f'\n{self.TAB}}}'
        return line

    def _expand_datasource_signal_info_setup_pre(self, signals):
        line = f'\n{self.TAB}if (ok) {{'
        line += f'\n{self.TAB}{self.TAB}ok = (GetNumberOfSignals() == ' + str(len(signals)) + ');'
        line += f'\n{self.TAB}{self.TAB}if (!ok) {{'
        line += f'\n{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Unexpected number of signals. Expected {0} and read %d", ' + str(len(signals)) + ', GetNumberOfSignals());'
        line += f'\n{self.TAB}{self.TAB}}}'
        line += f'\n{self.TAB}}}'
        return line

    def _expand_datasource_signal_info_setup(self, signal_name, signal_info, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        line = f'\n{self.TAB}if (ok) {{'
        line += self._expand_datasource_setup_signal_type(signal_name, signal_info, idx)
        line += f'\n{self.TAB}}}'
        number_of_elements_fixed = signal_info.get('number_of_elements_fixed', True)
        number_of_elements = signal_info.get('number_of_elements', 1)
        if number_of_elements > 1 or not number_of_elements_fixed:
            line += f'\n{self.TAB}if (ok) {{'
            line += self._expand_datasource_setup_signal_n_elements(signal_name, signal_info, number_of_elements_fixed, idx)
            line += f'\n{self.TAB}}}'
        return line

    def _expand_gam_setup_signal_type(self, signal_name, signal_info, signal_direction, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        signal_type = signal_info['type']
        signal_type_map = {
            'uint8': 'UnsignedInteger8Bit',
            'uint16': 'UnsignedInteger16Bit',
            'uint32': 'UnsignedInteger32Bit',
            'uint64': 'UnsignedInteger64Bit',
            'int8': 'SignedInteger8Bit',
            'int16': 'SignedInteger16Bit',
            'int32': 'SignedInteger32Bit',
            'int64': 'SignedInteger64Bit',
            'float32': 'Float32Bit',
            'float64': 'Float64Bit'}

        line = f'\n{self.TAB}{self.TAB}TypeDescriptor signalType{signal_name} = GetSignalType({signal_direction}, {idx});'
        line += f'\n{self.TAB}{self.TAB}ok = (signalType{signal_name} == {signal_type_map[signal_type]});' 
        line += f'\n{self.TAB}{self.TAB}if (!ok) {{' 
        line += f'\n{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Unexpected signal type for {signal_direction} at index {idx}");'
        line += f'\n{self.TAB}{self.TAB}}}'
        return line

    def _expand_datasource_setup_signal_type(self, signal_name, signal_info, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        signal_type = signal_info['type']
        signal_type_map = {
            'uint8': 'UnsignedInteger8Bit',
            'uint16': 'UnsignedInteger16Bit',
            'uint32': 'UnsignedInteger32Bit',
            'uint64': 'UnsignedInteger64Bit',
            'int8': 'SignedInteger8Bit',
            'int16': 'SignedInteger16Bit',
            'int32': 'SignedInteger32Bit',
            'int64': 'SignedInteger64Bit',
            'float32': 'Float32Bit',
            'float64': 'Float64Bit'}

        line = f'\n{self.TAB}{self.TAB}TypeDescriptor signalType{signal_name} = GetSignalType({idx});'
        line += f'\n{self.TAB}{self.TAB}ok = (signalType{signal_name} == {signal_type_map[signal_type]});' 
        line += f'\n{self.TAB}{self.TAB}if (!ok) {{' 
        line += f'\n{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Unexpected signal type at index {idx}");'
        line += f'\n{self.TAB}{self.TAB}}}'
        return line

    def _expand_gam_setup_signal_n_elements(self, signal_name, signal_info, signal_direction, number_of_elements_fixed, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        line = f'\n{self.TAB}{self.TAB}nOfElements{signal_name} = 0;'
        line += f'\n{self.TAB}{self.TAB}ok = GetSignalNumberOfElements({signal_direction}, {idx}, nOfElements{signal_name});'
        if number_of_elements_fixed:
            line += f'\n{self.TAB}{self.TAB}if (ok) {{' 
            line += f'\n{self.TAB}{self.TAB}{self.TAB}ok = (nOfElements{signal_name} == {signal_info["number_of_elements"]});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}if (!ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Expected %d elements and read %d for {signal_direction} at index {idx}", {signal_info["number_of_elements"]}, nOfElements{signal_name});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}}}'

        return line

    def _expand_datasource_setup_signal_n_elements(self, signal_name, signal_info, number_of_elements_fixed, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        line = f'\n{self.TAB}{self.TAB}nOfElements{signal_name} = 0;'
        line += f'\n{self.TAB}{self.TAB}ok = GetSignalNumberOfElements({idx}, nOfElements{signal_name});'
        if number_of_elements_fixed:
            line += f'\n{self.TAB}{self.TAB}if (ok) {{' 
            line += f'\n{self.TAB}{self.TAB}{self.TAB}ok = (nOfElements{signal_name} == {signal_info["number_of_elements"]});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}if (!ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Expected %d elements and read %d at index {idx}", {signal_info["number_of_elements"]}, nOfElements{signal_name});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}}}'

        return line


    def _expand_gam_setup_signal_samples(self, signal_name, signal_info, signal_direction, number_samples_fixed, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        line = f'\n{self.TAB}{self.TAB}nOfSamples{signal_name} = 0;'
        line += f'\n{self.TAB}{self.TAB}ok = GetSignalNumberOfSamples({signal_direction}, {idx}, nOfSamples{signal_name});'
        if number_samples_fixed:
            line += f'\n{self.TAB}{self.TAB}if (ok) {{' 
            line += f'\n{self.TAB}{self.TAB}{self.TAB}ok = (nOfSamples{signal_name} == {signal_info["samples"]});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}if (!ok) {{'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}{self.TAB}REPORT_ERROR(ErrorManagement::ParametersError, "Expected %d samples and read %d for {signal_direction} at index {idx}", {signal_info["samples"]}, nOfSamples{signal_name});'
            line += f'\n{self.TAB}{self.TAB}{self.TAB}}}'
            line += f'\n{self.TAB}{self.TAB}}}'

        return line

    def _expand_gam_setup_signal_memory(self, signal_name, signal_info, signal_direction, number_samples_fixed, idx):
        signal_name_lower_case = self._generate_lower_case_var(signal_name)
        signal_direction_no_s = signal_direction[:-1] # Remove the trailing 's' from 'InputSignals' or 'OutputSignals'
        signal_type = signal_info['type']
        line = f'\n{self.TAB}{self.TAB}{signal_name_lower_case} = reinterpret_cast<{signal_type} *>(Get{signal_direction_no_s}Memory({idx}));'
        return line

    def _generate_lower_case_var(self, name):
        ret = name
        match = re.match(r'^([A-Z]+)', name)
        if match:
            prefix = match.group(1)
            # If only one uppercase letter → lowercase it
            if len(prefix) == 1:
                new_prefix = prefix.lower()
            else:
                # Lowercase all but the last uppercase letter
                new_prefix = prefix[:-1].lower() + prefix[-1]
            ret = new_prefix + name[len(prefix):]
        return ret

    def _replace_autogenerated_section(self, filename, new_lines, autogenerated_start_marker, autogenerated_end_marker):
        ok = True
        with open(filename, 'r') as f:
            lines = f.readlines()

        start_idx = None
        end_idx = None

        # Find markers
        for i, line in enumerate(lines):
            if autogenerated_start_marker in line:
                start_idx = i
            elif autogenerated_end_marker in line:
                end_idx = i
                break  

        if start_idx is None or end_idx is None or start_idx >= end_idx:
            ok = False
            logger.critical(f'Markers not found or invalid in {filename}. Start idx: {start_idx}, End idx: {end_idx}, Start marker: {autogenerated_start_marker}, End marker: {autogenerated_end_marker}')

        if ok:
            updated_lines = (
                lines[:start_idx + 1] +   # keep start marker
                new_lines +               # insert new content
                lines[end_idx:]           # keep end marker + rest
            )

        # Write back
        if ok:
            with open(filename, 'w') as f:
                f.writelines(updated_lines)

        return ok

    def _add_component_folders(self):
        src_name = self._app_def_data['folders']['src']['name']
        test_name = self._app_def_data['folders']['test']['name']
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        comp_folder_name = self._comp_name
        folders = {
            self._project_name: {
                src_name: {
                    comp_type_name: {
                        comp_folder_name: {}
                    }
                },
                test_name: {
                    comp_type_name: {
                        comp_folder_name: {}
                    }
                }
            }
        }
        return self._create_folders(self._project_path, folders, only_leafs=True)

    def _add_component_files(self):
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        src_file_template_name = self._app_def_data['components'][self._comp_type]['src_template_name'] + '.cpp'
        h_file_template_name = self._app_def_data['components'][self._comp_type]['src_template_name'] + '.h'
        test_src_file_template_name = self._app_def_data['components'][self._comp_type]['test_template_name'] + '.cpp'
        test_h_file_template_name = self._app_def_data['components'][self._comp_type]['test_template_name'] + '.h'
        gtest_src_file_template_name = self._app_def_data['components'][self._comp_type]['gtest_template_name'] + '.cpp'

        src_folder_name = self._app_def_data['folders']['src']['name']
        test_folder_name = self._app_def_data['folders']['test']['name']
        template_cpp_vars = copy.deepcopy(self._template_cpp_vars)
        template_h_vars = copy.deepcopy(self._template_h_vars)

        template_cpp_vars['file'] = f'{self._comp_name}.cpp'
        template_cpp_vars['class'] = self._comp_name
        template_cpp_vars['namespace'] = self._comp_namespace

        template_h_vars['file'] = f'{self._comp_name}.h'
        template_h_vars['class'] = self._comp_name
        template_h_vars['namespace'] = self._comp_namespace
        template_h_vars['header_guard'] = f'_{self._comp_namespace.upper()}_{self._comp_name.upper()}_H_' 

        ok = self._copy_template_text_file(src_file_template_name, Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name, template_cpp_vars, target_name=f'{self._comp_name}.cpp')
        if ok:
            ok = self._copy_template_text_file(h_file_template_name, Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name, template_h_vars, target_name=f'{self._comp_name}.h')
        if ok:
            template_cpp_vars['file'] = f'{self._comp_name}Test.cpp'
            template_cpp_vars['class'] = f'{self._comp_name}Test'
            ok = self._copy_template_text_file(test_src_file_template_name, Path(self._project_path) / self._project_name / test_folder_name / comp_type_name / self._comp_name, template_cpp_vars, target_name=f'{self._comp_name}Test.cpp')
        if ok:
            template_h_vars['file'] = f'{self._comp_name}Test.h'
            template_h_vars['class'] = f'{self._comp_name}Test'
            template_h_vars['src_class'] = f'{self._comp_name}'
            template_h_vars['header_guard'] = f'_{self._comp_namespace.upper()}_{self._comp_name.upper()}_TEST_H_' 
            ok = self._copy_template_text_file(test_h_file_template_name, Path(self._project_path) / self._project_name / test_folder_name / comp_type_name / self._comp_name, template_h_vars, target_name=f'{self._comp_name}Test.h')

        if ok:
            template_cpp_vars['file'] = f'{self._comp_name}GTest.cpp'
            template_cpp_vars['class'] = f'{self._comp_name}GTest'
            template_cpp_vars['src_class'] = f'{self._comp_name}Test'
            ok = self._copy_template_text_file(gtest_src_file_template_name, Path(self._project_path) / self._project_name / test_folder_name / comp_type_name / self._comp_name, template_cpp_vars, target_name=f'{self._comp_name}GTest.cpp')

        return ok

    def _add_makefiles(self):
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        src_folder_name = self._app_def_data['folders']['src']['name']
        test_folder_name = self._app_def_data['folders']['test']['name']
        template_make_vars = copy.deepcopy(self._template_make_vars)

        template_make_vars['root_dir'] = '../../../'
        template_make_vars['package'] = f'PACKAGE = {comp_type_name}'
        template_make_vars['objsx'] = f'{self._comp_name}.x'
        template_make_vars['includes'] = self._get_marte2_includes() 
        template_make_vars['target_1'] = f'all: $(OBJS) $(SUBPROJ) check-env \\\n\t$(BUILD_DIR)/{self._comp_name}$(LIBEXT) \\\n\t$(BUILD_DIR)/{self._comp_name}$(DLLEXT)\n\techo  $(OBJS)' 

        for makefile_name in ['Makefile.inc', 'Makefile.gcc', 'Makefile.cov']:
            ok = self._copy_template_text_file(makefile_name, Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / self._comp_name, template_make_vars)
            if not ok:
                break

        template_make_vars['package'] = f'PACKAGE = {comp_type_name}'
        template_make_vars['objsx'] = f'{self._comp_name}Test.x\\\n\t{self._comp_name}GTest.x'
        template_make_vars['includes'] = self._get_marte2_includes() 
        template_make_vars['includes'] += f'\nINCLUDES += -I$(ROOT_DIR)/{src_folder_name}/{comp_type_name}/{self._comp_name}' 
        template_make_vars['includes'] += '\nINCLUDES += -I$(MARTe2_DIR)/Lib/gtest-1.7.0/include'
        template_make_vars['target_1'] = f'all: $(OBJS) $(SUBPROJ) check-env \\\n\t$(BUILD_DIR)/{self._comp_name}Test$(LIBEXT)\n\techo  $(OBJS)' 

        for makefile_name in ['Makefile.inc', 'Makefile.gcc', 'Makefile.cov']:
            if not ok:
                break
            ok = self._copy_template_text_file(makefile_name, Path(self._project_path) / self._project_name / test_folder_name / comp_type_name / self._comp_name, template_make_vars)

        return ok

    def _patch_parent_makefiles(self):
        comp_type_name = self._app_def_data['components'][self._comp_type]['name']
        src_folder_name = self._app_def_data['folders']['src']['name']
        test_folder_name = self._app_def_data['folders']['test']['name']

        makefile_path = Path(self._project_path) / self._project_name / src_folder_name / comp_type_name / 'Makefile.inc'
        ok = self._patch_makefile_assignment(makefile_path, 'SPB', f'{self._comp_name}.x')
        if ok:
            makefile_path = Path(self._project_path) / self._project_name / test_folder_name / comp_type_name / 'Makefile.inc'
            ok = self._patch_makefile_assignment(makefile_path, 'SPB', f'{self._comp_name}.x')
        return ok

    def _patch_makefile_assignment(self, makefile_path, var_name, var_value):
        ok = True
        try:
            with open(makefile_path, 'r') as f:
                makefile_text = f.read()
            pattern = re.compile(r"(^SPB\s*=\s*)(.*?)(?=^\S.*=|\Z)", re.MULTILINE | re.DOTALL,)
            match = pattern.search(makefile_text)
            if match:
                prefix = match.group(1)
                body = match.group(2)
                # Collect current entries, removing line continuations and extra spaces
                prefix = prefix.replace('\\\n\t', ' ').strip()
                existing_entries = body.replace('\\\n\t', ' ').strip()
                entries = [item for item in existing_entries.split() if item]
                logger.debug(f'In {makefile_path}, current entries for {var_name}: {entries}')
                if var_value not in entries:
                    entries.append(var_value)
                new_content = f'{prefix} {entries[0]} \\'
                for entry in entries[1:]:
                    new_content += f'\n\t{entry} \\'
                new_content = new_content[:-1] # Remove the last \
            else:
                new_content = f'{prefix} = {var_value}'
            new_content += '\n\n'
            start, end = match.span()
            new_makefile_text = makefile_text[:start] + new_content + makefile_text[end:]
            with open(makefile_path, 'w') as f:
                f.write(new_makefile_text)
        except Exception as e:
            logger.error(f'Failed to patch makefile {makefile_path}: {e}')
            ok = False
        return ok

    def _get_marte2_includes(self):
        includes = []

        includes.append('INCLUDES += -I.')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L0Types')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L1Portability')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L2Objects')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L3Streams')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L4Configuration')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L4HttpService')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L4Logger')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L4Messages')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L5GAMs')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L6App')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/FileSystem/L1Portability')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/FileSystem/L3Streams')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/FileSystem/L4HttpService')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/FileSystem/L4LoggerService')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/FileSystem/L6App')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/Scheduler/L1Portability')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/Scheduler/L3Services')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/Scheduler/L4LoggerService')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/Scheduler/L4Messages')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/Scheduler/L4StateMachine')
        includes.append('INCLUDES += -I$(MARTe2_DIR)/Source/Core/Scheduler/L5GAMs')

        return '\n'.join(includes)

    def _add_component_templates(self, comp_folder_name):
        ok = True
        return ok

    def _patch_startup_marte_app_sh(self):
        ok = True
        startup_folder_name = self._app_def_data['folders']['startup']['name']
        marte_app_sh_path = Path(self._project_path) / self._project_name / startup_folder_name / 'MARTeApp.sh'

        with open(marte_app_sh_path, "r") as f:
            lines = f.readlines()

        target_prefix = "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
        last_index = -1

        # Find the last occurrence
        for i, line in enumerate(lines):
            if line.strip().startswith(target_prefix):
                last_index = i
        
        # If found, insert new line after it
        ok = last_index != -1
        if ok:
            comp_type_name = self._app_def_data['components'][self._comp_type]['name']
            new_ld_lib_path = f'../Build/x86-linux/{comp_type_name}/{self._comp_name}'
 
            new_line = f'{target_prefix}:{new_ld_lib_path}\n'
            lines.insert(last_index + 1, new_line)
            with open(marte_app_sh_path, "w") as f:
                f.writelines(lines)
        else:
            logger.critical(f'Failed to patch {marte_app_sh_path}: could not find line starting with "{target_prefix}"')
        return ok