#############################################################
#
# Copyright 2015 EFDA | European Joint Undertaking for ITER
# and the Development of Fusion Energy ("Fusion for Energy")
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.linux 3 2012-01-15 16:26:07Z aneto $
#
#############################################################

TARGET=cov

include Makefile.inc

LIBRARIES_STATIC=L0Types/cov/L0TypesBGTest$(LIBEXT)
LIBRARIES_STATIC+= L1Portability/cov/L1PortabilityBGTest$(LIBEXT)
LIBRARIES_STATIC+= L2Objects/cov/L2ObjectsBGTest$(LIBEXT)
LIBRARIES_STATIC+= L3Streams/cov/L3StreamsBGTest$(LIBEXT)
LIBRARIES_STATIC+= L4Configuration/cov/L4ConfigurationBGTest$(LIBEXT)
LIBRARIES_STATIC+= L4Logger/cov/L4LoggerBGTest$(LIBEXT)
LIBRARIES_STATIC+= L4HttpService/cov/L4HttpServiceBGTest$(LIBEXT)
LIBRARIES_STATIC+= L4Messages/cov/L4MessagesBGTest$(LIBEXT)
LIBRARIES_STATIC+= L5GAMs/cov/L5GAMsBGTest$(LIBEXT)
LIBRARIES_STATIC+= L6App/cov/L6AppBGTest$(LIBEXT)
