#############################################################
#
# Copyright 2015 EFDA | European Joint Undertaking for ITER
# and the Development of Fusion Energy ("Fusion for Energy")
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.gcc 3 2015-01-15 16:26:07Z aneto $
#
#############################################################

TARGET=pack

OBJSX= Source.x Lib.x MakeDefaults.x Makefile.x86-linux.x Makefile.inc.x Test.x Docs.x

MARTe2_MAKEDEFAULT_DIR?=MakeDefaults

ROOT_DIR=.
include $(MARTe2_MAKEDEFAULT_DIR)/MakeStdLibDefs.$(TARGET)

# Optionally do [make -f Makefile.pack BUILD_OPT=...] to build with that target 

all: $(OBJS) $(BUILD_DIR)/RPMS/$(RPM_NAME)-$(BUILD_OPT)-$(RPM_VERSION).rpm  
	echo  $(OBJS)

include $(MARTe2_MAKEDEFAULT_DIR)/MakeStdLibRules.$(TARGET)