[project]
name = "marte2-manager"
version = "1.0.0"
description = "CLI tool to manage MARTe2 projects"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
marte2ctl = "marte2_manager.cli:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
marte2_manager = ["templates/*.*"]

