
// SlkConstants.h - generated by the SLK parser generator 

#ifndef _SlkCONSTANTS_H
#define _SlkCONSTANTS_H

enum _Slk_token_defines { 
  LESS_ = 1 
, STRING_ = 2 
, GREATER_ = 3 
, SLASH_ = 4 
, LPAREN_ = 5 
, RPAREN_ = 6 
, LBRACE_ = 7 
, RBRACE_ = 8 
, NUMBER_ = 9 
, END_OF_SLK_INPUT_ = 10 
}; 

enum _Slk_Nonterminal_defines { 
  NT_EXPRESSION_ = 11 
, NT_CDBFILE_ = 12 
, NT_EXPRESSIONS_ = 13 
, NT_VARIABLES_ = 14 
, NT_SCALAR_ = 15 
, NT_VECTOR_ = 16 
, NT_MATRIX_ = 17 
, NT_BLOCK_ = 18 
, NT_TOKEN_ = 19 
, NT_EXPRESSIONS_STAR_ = 20 
, NT_SCALAR_STAR_ = 21 
, NT_VECTOR_STAR_ = 22 
, NT_EXPRESSIONS_2_STAR_ = 23 
}; 

typedef unsigned short   slk_size_t;

#define NOT_A_SYMBOL       0
#define NONTERMINAL_SYMBOL 1
#define TERMINAL_SYMBOL    2
#define ACTION_SYMBOL      3

int SlkGetSymbolType ( slk_size_t symbol );
slk_size_t *SlkGetProductionArray ( slk_size_t   production_number );
slk_size_t *SlkGetState ( slk_size_t  state_number );
int SlkIsNonterminal ( slk_size_t symbol );
int SlkIsTerminal ( slk_size_t symbol );
int SlkIsAction ( slk_size_t symbol );


#endif
