
// SlkConstants.h - generated by the SLK parser generator 

#ifndef _SlkCONSTANTS_H
#define _SlkCONSTANTS_H

enum _Slk_token_defines { 
  STRING_ = 1 
, EQUAL_ = 2 
, LPAREN_ = 3 
, RPAREN_ = 4 
, LBRACE_ = 5 
, RBRACE_ = 6 
, NUMBER_ = 7 
, END_OF_SLK_INPUT_ = 8 
}; 

enum _Slk_Nonterminal_defines { 
  NT_EXPRESSION_ = 9 
, NT_CDBFILE_ = 10 
, NT_EXPRESSIONS_ = 11 
, NT_VARIABLES_ = 12 
, NT_SCALAR_ = 13 
, NT_VECTOR_ = 14 
, NT_MATRIX_ = 15 
, NT_BLOCK_ = 16 
, NT_TOKEN_ = 17 
, NT_EXPRESSIONS_STAR_ = 18 
, NT_SCALAR_STAR_ = 19 
, NT_VECTOR_STAR_ = 20 
, NT_EXPRESSIONS_2_STAR_ = 21 
}; 

typedef unsigned short   slk_size_t;

#define NOT_A_SYMBOL       0
#define NONTERMINAL_SYMBOL 1
#define TERMINAL_SYMBOL    2
#define ACTION_SYMBOL      3

int SlkGetSymbolType ( slk_size_t symbol );
slk_size_t *SlkGetProductionArray ( slk_size_t   production_number );
slk_size_t *SlkGetState ( slk_size_t  state_number );
int SlkIsNonterminal ( slk_size_t symbol );
int SlkIsTerminal ( slk_size_t symbol );
int SlkIsAction ( slk_size_t symbol );


#endif
