
// SlkString.h - generated by the SLK parser generator 

#ifndef _SlkSTRING_H
#define _SlkSTRING_H

namespace MARTe {

char *SlkGetSymbolName ( unsigned int   symbol );
char *SlkGetProductionName ( unsigned int  production_number );



}

#endif
