
// SlkTable.h - generated by the SLK parser generator 

#ifndef _SlkTABLE_H
#define _SlkTABLE_H

public:

void    End ( void );
void    GetNodeName ( void );
void    AddLeaf ( void );
void    GetTypeCast ( void );
void    CreateNode ( void );
void    BlockEnd ( void );
void    AddScalar ( void );
void    EndRow ( void );

void    ( SlkAction::*Action [ 9 ] ) ( void );

void    initialize_table ( void );
void
execute ( int  number )   { ( this->*Action [ number ] ) (); }

#endif
