
// SlkTerminals.h - generated by the SLK parser generator 

// Declaration of terminals values as int, can be used to seed the symbol table with terminals

#ifndef _SlkTERMINALS_H
#define _SlkTERMINALS_H

#include "SlkConstants.h" 

typedef struct _Slk_terminal { 
    slk_size_t  token;
    char  *name;
} Slk_terminal_t;

static Slk_terminal_t Slk_terminal [] = { 
 { LESS_, "<" } 
,{ STRING_, "STRING" } 
,{ GREATER_, ">" } 
,{ SLASH_, "/" } 
,{ LPAREN_, "(" } 
,{ RPAREN_, ")" } 
,{ LBRACE_, "{" } 
,{ RBRACE_, "}" } 
,{ NUMBER_, "NUMBER" } 
,{ END_OF_SLK_INPUT_, "END_OF_SLK_INPUT" } 
,{ 0, NULL } 
}; 


#endif
