
// SlkTable.cpp - generated by the SLK parser generator 

#include "SlkAction.h"

void
SlkAction ::
initialize_table ( void )
{
    Action [ 0 ] = 0;
    Action [ 1 ] = &SlkAction::End;
    Action [ 2 ] = &SlkAction::GetNodeName;
    Action [ 3 ] = &SlkAction::AddLeaf;
    Action [ 4 ] = &SlkAction::GetTypeCast;
    Action [ 5 ] = &SlkAction::CreateNode;
    Action [ 6 ] = &SlkAction::BlockEnd;
    Action [ 7 ] = &SlkAction::AddScalar;
    Action [ 8 ] = &SlkAction::EndRow;
}
