#############################################################
#
# Copyright 2015 EFDA | European Joint Undertaking for ITER
# and the Development of Fusion Energy ("Fusion for Energy")
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http:\\ec.europa.eu\idabc\eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.msc 3 2012-01-15 16:26:07Z aneto $
#
#############################################################
TARGET=msc

include Makefile.inc


OBJSO= $(shell dir $(BUILD_DIR)\BareMetal\*.obj /b/s)
OBJSO+= $(shell dir $(BUILD_DIR)\Scheduler\*.obj /b/s)
OBJSO+= $(shell dir $(BUILD_DIR)\FileSystem\*.obj /b/s)

OBJSX=$(OBJSO:$(BUILD_DIR)\%.obj=%.x)

CPPFLAGS+= -fprofile-arcs -ftest-coverage -coverage
INCLUDES += -I../../Lib/gtest-1.7.0/include

LIBRARIES   += ..\..\Build\$(TARGET)\Core\MARTe2$(LIBEXT) 
LIBRARIES   += ..\..\Build\$(TARGET)\Core\BareMetal\MARTeCoreBTest$(LIBEXT) 
LIBRARIES   += ..\..\Build\$(TARGET)\Core\Scheduler\MARTeCoreSTest$(LIBEXT)
LIBRARIES   += ..\..\Build\$(TARGET)\Core\FileSystem\MARTeCoreFTest$(LIBEXT)



LIBRARIES   += ..\..\Lib\gtest-1.7.0\gtest_main-md.lib ..\..\Lib\gtest-1.7.0\gtest-md.lib 
LIBRARIES   += Winmm.lib
