#############################################################
#
# Copyright 2011 EFDA | European Fusion Development Agreement
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http:\\ec.europa.eu\idabc\eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.msc 3 2012-01-15 16:26:07Z aneto $
#
#############################################################
TARGET=msc

include Makefile.inc


OBJSO= $(shell dir $(BUILD_DIR)\BareMetal\*.obj /b/s)
OBJSO+= $(shell dir $(BUILD_DIR)\Scheduler\*.obj /b/s)
OBJSO+= $(shell dir $(BUILD_DIR)\FileSystem\*.obj /b/s)

OBJSX=$(OBJSO:$(BUILD_DIR)\%.obj=%.x)

#BareMetal\L0Types\BasicTypeGTest.x \
		BareMetal\L0Types\BitBooleanGTest.x \
		BareMetal\L0Types\BitRangeGTest.x \
		BareMetal\L0Types\DoubleIntegerGTest.x \
		BareMetal\L0Types\FractionalIntegerGTest.x \
		BareMetal\L0Types\LinkedListHolderGTest.x \
		BareMetal\L0Types\LinkedListableGTest.x \
		BareMetal\L0Types\MatrixGTest.x \
		BareMetal\L0Types\ShiftGTest.x \
		BareMetal\L0Types\TypeCharacteristicsGTest.x \
		BareMetal\L0Types\TypeDescriptorGTest.x \
		BareMetal\L0Types\VectorGTest.x \
		BareMetal\L1Portability\AtomicGTest.x \
		BareMetal\L1Portability\BasicConsoleGTest.x \
		BareMetal\L1Portability\EndianityGTest.x \
		BareMetal\L1Portability\ErrorManagementGTest.x \
		BareMetal\L1Portability\FastMathGTest.x \
		BareMetal\L1Portability\FastPollingMutexSemGTest.x \
		BareMetal\L1Portability\FormatDescriptorGTest.x \
		BareMetal\L1Portability\GlobalObjectsDatabaseGTest.x \
		BareMetal\L1Portability\HeapManagerGTest.x \
		BareMetal\L1Portability\HighResolutionTimerGTest.x \
		BareMetal\L1Portability\LoadableLibraryGTest.x \
		BareMetal\L1Portability\MemoryCheckGTest.x\
		BareMetal\L1Portability\MemoryOperationsHelperGTest.x\
		BareMetal\L1Portability\ProcessorTypeGTest.x \
		BareMetal\L1Portability\SleepGTest.x\
		BareMetal\L1Portability\StandardHeap_GenericGTest.x \
		BareMetal\L1Portability\StaticListGTest.x \
		BareMetal\L1Portability\StringHelperGTest.x \
		BareMetal\L1Portability\StringPortableGTest.x \
		BareMetal\L1Portability\TimeStampGTest.x \
		BareMetal\L1Portability\TimeoutTypeGTest.x \
		BareMetal\L2Objects\AnyTypeGTest.x \
		BareMetal\L2Objects\ClassPropertiesGTest.x \
		BareMetal\L2Objects\ClassRegistryDatabaseGTest.x \
		BareMetal\L2Objects\ClassRegistryItemGTest.x \
		BareMetal\L2Objects\ObjectGTest.x \
		BareMetal\L2Objects\ReferenceContainerFilterObjectNameGTest.x \
		BareMetal\L2Objects\ReferenceContainerFilterReferencesGTest.x \
		BareMetal\L2Objects\ReferenceContainerGTest.x \
		BareMetal\L2Objects\ReferenceContainerNodeGTest.x \
		BareMetal\L2Objects\ReferenceGTest.x \
		BareMetal\L2Objects\ReferenceTGTest.x \
		BareMetal\L3Streams\BitSetToIntegerGTest.x \
		BareMetal\L3Streams\BufferedStreamIGTest.x \
		BareMetal\L3Streams\BufferedStreamIOBufferGTest.x \
		BareMetal\L3Streams\CharBufferGTest.x \
		BareMetal\L3Streams\DoubleBufferedStreamGTest.x \
		BareMetal\L3Streams\IOBufferGTest.x \
		BareMetal\L3Streams\SingleBufferedStreamGTest.x \
		BareMetal\L3Streams\StreamMemoryReferenceGTest.x \
		BareMetal\L3Streams\StreamStringGTest.x \
		BareMetal\L3Streams\StreamStringIOBufferGTest.x \
		BareMetal\L4Configuration\AnyObjectGTest.x \
		BareMetal\L4Configuration\AnyTypeCreatorGTest.x \
		BareMetal\L4Configuration\ConfigurationDatabaseGTest.x \
		BareMetal\L4Configuration\JsonParserGTest.x \
		BareMetal\L4Configuration\LexicalAnalyzerGTest.x \
		BareMetal\L4Configuration\StandardParserGTest.x \
		BareMetal\L4Configuration\TokenGTest.x \
		BareMetal\L4Configuration\TokenInfoGTest.x \
		BareMetal\L4Configuration\TypeConversionGTest.x\
		BareMetal\L4Configuration\XMLParserGTest.x\
		FileSystem\L1Portability\BasicFileGTest.x \
		FileSystem\L1Portability\BasicSocketGTest.x\
		FileSystem\L1Portability\BasicTCPSocketGTest.x \
		FileSystem\L1Portability\BasicUDPSocketGTest.x \
		FileSystem\L1Portability\DirectoryGTest.x \
		FileSystem\L1Portability\DirectoryScannerGTest.x \
		FileSystem\L1Portability\InternetHostGTest.x \
		FileSystem\L1Portability\InternetServiceGTest.x \
		FileSystem\L1Portability\SelectGTest.x \
		Scheduler\L1Portability\EventSemGTest.x\
		Scheduler\L1Portability\MutexSemGTest.x\
		Scheduler\L1Portability\ProcessorGTest.x\
		Scheduler\L1Portability\ThreadsGTest.x
		
		




CPPFLAGS+= -fprofile-arcs -ftest-coverage -coverage
INCLUDES += -I../../Lib/gtest-1.7.0/include

LIBRARIES   += ..\..\Build\$(TARGET)\Core\MARTe2$(LIBEXT) 
LIBRARIES   += ..\..\Build\$(TARGET)\Core\BareMetal\MARTeCoreBTest$(LIBEXT) 
LIBRARIES   += ..\..\Build\$(TARGET)\Core\Scheduler\MARTeCoreSTest$(LIBEXT)
LIBRARIES   += ..\..\Build\$(TARGET)\Core\FileSystem\MARTeCoreFTest$(LIBEXT)



LIBRARIES   += ..\..\Lib\gtest-1.7.0\gtest_main-md.lib ..\..\Lib\gtest-1.7.0\gtest-md.lib 
LIBRARIES   += Winmm.lib
