#############################################################
#
# Copyright 2015 EFDA | European Joint Undertaking for ITER
# and the Development of Fusion Energy ("Fusion for Energy")
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http:\\ec.europa.eu\idabc\eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.msc 3 2012-01-15 16:26:07Z aneto $
#
#############################################################
TARGET=msc

LIBRARIES+=..\..\Build\$(TARGET)\Core\MARTe2$(LIBEXT) 
LIBRARIES+=..\..\Build\$(TARGET)\Core\BareMetal\MARTeCoreBTest$(LIBEXT) 
LIBRARIES+=..\..\Build\$(TARGET)\Core\Scheduler\MARTeCoreSTest$(LIBEXT)
LIBRARIES+=..\..\Build\$(TARGET)\Core\FileSystem\MARTeCoreFTest$(LIBEXT)

include Makefile.inc

#OBJSO=$(shell dir $(BUILD_DIR)\BareMetal\*.obj /b/s)
#OBJSO+=$(shell dir $(BUILD_DIR)\Scheduler\*.obj /b/s)
#OBJSO+=$(shell dir $(BUILD_DIR)\FileSystem\*.obj /b/s)

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\BasicFileGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\BasicTypeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\Core\BareMetal\L0Types\BasicTypeTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\StaticListGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\StaticStackGTest.obj

#TESTSBYLAYER
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\BitBooleanGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\BitRangeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\BitSetGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\CRCGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\DjbHashFunctionGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\DoubleIntegerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\ErrorTypeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\Fnv1aHashFunctionGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\FractionalIntegerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\LinkedListableGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\LinkedListHolderGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\MatrixGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\ShiftGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\TypeCharacteristicsGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\VectorGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L0Types\ZeroTerminatedArrayGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\AtomicGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\BasicConsoleGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\BinaryTreeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\CircularStaticListGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\EndianityGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\ErrorManagementGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\FastMathGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\FastPollingEventSemGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\FastPollingMutexSemGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\FastResourceContainerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\FormatDescriptorGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\GlobalObjectsDatabaseGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\HeapManagerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\HighResolutionTimerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\LoadableLibraryGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\Md5EncryptGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\MemoryAreaGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\MemoryCheckGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\MemoryOperationsHelperGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\ProcessorTypeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\SafeMathGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\SleepGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\StandardHeap_GenericGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\StaticListGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\StaticStackGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\StringHelperGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\StringPortableGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\TimeoutTypeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\TimeStampGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L1Portability\TypeDescriptorGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\AnyTypeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ClassMethodCallerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ClassMethodCallerTGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ClassMethodInterfaceMapperGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ClassMethodsRegistryItemGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ClassPropertiesGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ClassRegistryDatabaseGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ClassRegistryItemGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\IntrospectionEntryGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\IntrospectionGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ObjectBuilderGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ObjectBuilderTGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ObjectGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ObjectRegistryDatabaseGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ReferenceContainerFilterNameAndTypeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ReferenceContainerFilterObjectNameGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ReferenceContainerFilterReferencesGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ReferenceContainerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ReferenceContainerNodeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ReferenceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L2Objects\ReferenceTGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\AdvancedErrorManagementGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\Base64EncoderGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\BitSetToIntegerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\BufferedStreamIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\BufferedStreamIOBufferGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\CharBufferGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\DoubleBufferedStreamGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\IOBufferGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\JsonPrinterGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\PrinterIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\SingleBufferedStreamGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\StandardPrinterGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\StreamMemoryReferenceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\StreamStringGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\StreamStringIOBufferGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\StreamStructuredDataGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\StreamStructuredDataIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L3Streams\XMLPrinterGTest.obj

#OBJSO=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\AnyObjectGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\AnyTypeCreatorGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\ConfigurationDatabaseGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\ConfigurationDatabaseNodeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\IntrospectionStructureGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\JsonParserGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\LexicalAnalyzerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\MathExpressionParserGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\RuntimeEvaluatorFunctionGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\RuntimeEvaluatorGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\StandardParserGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\StructuredDataIHelperGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\TokenGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\TokenInfoGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\TypeConversionGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\ValidateBasicTypeGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Configuration\XMLParserGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4HttpService\HttpDefinitionGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Logger\LoggerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Messages\MessageFilterPoolGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Messages\MessageGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Messages\MessageIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Messages\ObjectRegistryDatabaseMessageFilterGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Messages\ObjectRegistryDatabaseMessageIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Messages\RegisteredMethodsMessageFilterGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L4Messages\ReplyMessageCatcherMessageFilterGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\BrokerIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\DataSourceIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\ExecutableIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\GAMBareSchedulerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\GAMDataSourceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\GAMGroupGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\GAMGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\GAMSchedulerIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryDataSourceIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapInputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapInterpolatedInputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapMultiBufferBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapMultiBufferInputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapMultiBufferOutputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapOutputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapSynchronisedInputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapSynchronisedMultiBufferInputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapSynchronisedMultiBufferOutputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\MemoryMapSynchronisedOutputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\RealTimeApplicationConfigurationBuilderGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\RealTimeApplicationGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\RealTimeStateGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\RealTimeThreadGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L5GAMs\TimingDataSourceGTest.obj

OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L6App\ConfigurationLoaderHashCRCGTest.obj
OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L6App\LoaderGTest.obj
OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\BareMetal\L6App\RealTimeLoaderGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\BasicFileGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\BasicSocketGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\BasicTCPSocketGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\BasicUARTGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\BasicUDPSocketGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\DirectoryGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\DirectoryScannerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\InternetHostGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\InternetServiceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L1Portability\SelectGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L3Streams\FileGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L3Streams\TCPSocketGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L3Streams\UDPSocketGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4HttpService\HttpChunkedStreamGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4HttpService\HttpClientGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4HttpService\HttpDataExportIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4HttpService\HttpDirectoryResourceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4HttpService\HttpMessageInterfaceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4HttpService\HttpObjectBrowserGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4HttpService\HttpProtocolGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4HttpService\HttpServiceGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L4LoggerService\UDPLoggerGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L6App\BootstrapGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\FileSystem\L6App\ConfigurationLoaderTCPGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L1Portability\CountingSemGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L1Portability\EventSemGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L1Portability\MutexSemGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L1Portability\ProcessorGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L1Portability\ThreadsGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\EmbeddedServiceMethodBinderTGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\EmbeddedThreadGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\EmbeddedThreadIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\ExecutionInfoGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\MultiClientEmbeddedThreadGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\MultiClientServiceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\MultiThreadServiceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\SingleThreadServiceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L3Services\ThreadsInformationQueryGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L4LoggerService\ConsoleLoggerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L4LoggerService\LoggerConsumerIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L4LoggerService\LoggerServiceGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L4Messages\QueuedMessageIGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L4Messages\QueuedReplyMessageCatcherFilterGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L4Messages\QueueingMessageFilterGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L4StateMachine\StateMachineEventGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L4StateMachine\StateMachineGTest.obj

#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L5GAMs\CircularBufferThreadInputDataSourceGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L5GAMs\FastSchedulerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L5GAMs\GAMSchedulerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L5GAMs\MemoryMapAsyncOutputBrokerGTest.obj
#OBJSO+=C:\Users\peppe\Projects\MARTe2\Build\msc\GTest\Scheduler\L5GAMs\MemoryMapAsyncTriggerOutputBrokerGTest.obj

#ENDTESTSBYLAYER


OBJSX=$(OBJSO:$(BUILD_DIR)\%.obj=%.x)

#CPPFLAGS+=-fprofile-arcs -ftest-coverage -coverage
INCLUDES+=-I../

#LIBRARIES+=..\..\Lib\gtest-1.7.0\gtest_main-md.lib ..\..\Lib\gtest-1.7.0\gtest-md.lib 
#LIBRARIES+=Winmm.lib
