#############################################################
#
# Copyright 2011 EFDA | European Fusion Development Agreement
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.linux 3 2012-01-15 16:26:07Z aneto $
#
#############################################################

TARGET=cov

include Makefile.inc

LIBRARIES   += ../../Source/Core/L0Portability/$(TARGET)/L0Portability$(LIBEXT) 
LIBRARIES   += ../../Source/Core/L1CLib/$(TARGET)/L1CLib$(LIBEXT) 
LIBRARIES   += ../../Source/Core/LXTypeDev/$(TARGET)/LXTypeDev$(LIBEXT)
LIBRARIES   += ../../Test/Core/L0Portability/$(TARGET)/L0PortabilityTest$(LIBEXT) 
LIBRARIES   += ../../Test/Core/L1CLib/$(TARGET)/L1CLibTest$(LIBEXT) 
LIBRARIES   += ../../Test/Core/LXTypeDev/$(TARGET)/LXTypeDevTest$(LIBEXT)
LIBRARIES   += ../../Lib/gtest-1.7.0/libgtest.a ../../Lib/gtest-1.7.0/libgtest_main.a 


OPTIM=-finline-functions

