#############################################################
#
# Copyright 2015 F4E | European Joint Undertaking for ITER 
#  and the Development of Fusion Energy ('Fusion for Energy')
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.linux 3 2012-01-15 16:26:07Z aneto $
#
#############################################################

TARGET=freertos-armv7m

OBJSX=  AtomicGTest.x \
		BasicConsoleGTest.x \
		EndianityGTest.x \
		FormatDescriptorGTest.x \
		GlobalObjectsDatabaseGTest.x \
		HeapManagerGTest.x \
		HighResolutionTimerGTest.x \
		MemoryGTest.x \
		SleepGTest.x \
		StandardHeap_GenericGTest.x \
		StaticListGTest.x \
		StringHelperGTest.x \
		StringPortableGTest.x \
		TimeStampGTest.x \
		TimeoutTypeGTest.x
#ErrorManagementGTest.x \
		FastMathGTest.x \
		LoadableLibraryGTest.x \
		FastPollingMutexSemGTest.x 
		
		 


PACKAGE=GTest/BareMetal
ROOT_DIR=../../../..
MAKEDEFAULTDIR=$(ROOT_DIR)/MakeDefaults

include $(MAKEDEFAULTDIR)/MakeStdLibDefs.$(TARGET)


INCLUDES += -I../../../
INCLUDES += -I../../../Core/BareMetal/L0Types
INCLUDES += -I../../../Core/BareMetal/L1Portability
INCLUDES += -I../../../Core/BareMetal/L2Objects
INCLUDES += -I../../../Core/BareMetal/L3Streams
INCLUDES += -I../../../Core/BareMetal/L4Configuration
INCLUDES += -I../../../Core/Scheduler/L1Portability
INCLUDES += -I../../../Core/FileSystem/L1Portability
INCLUDES += -I../../../../Source/Core/BareMetal/L0Types
INCLUDES += -I../../../../Source/Core/BareMetal/L1Portability
INCLUDES += -I../../../../Source/Core/BareMetal/L2Objects
INCLUDES += -I../../../../Source/Core/BareMetal/L3Streams
INCLUDES += -I../../../../Source/Core/BareMetal/L4Configuration
INCLUDES += -I../../../../Source/Core/Scheduler/L1Portability
INCLUDES += -I../../../../Source/Core/FileSystem/L1Portability
INCLUDES += -I../../../../Lib/EmbeddedTestEngine


all: $(OBJS)    \
        $(BUILD_DIR)/L1PortabilityBGTest$(LIBEXT) 
	echo  $(OBJS)

include depends.$(TARGET)

include $(MAKEDEFAULTDIR)/MakeStdLibRules.$(TARGET)


