#############################################################
#
# Copyright 2011 EFDA | European Fusion Development Agreement
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.msc 3 2012-01-15 16:26:07Z aneto $
#
#############################################################
TARGET=msc

include Makefile.inc

LIBRARIES0   = kernel32.lib wsock32.lib largeint.lib user32.lib advapi32.lib ws2_32.lib
LIBRARIES   += $(LIBRARIES0) $(BLCOMPONENTS)

LIBRARIES_STATIC+=$(BUILD_DIR)/L0Types/L0TypesTest$(LIBEXT)
LIBRARIES_STATIC+=$(BUILD_DIR)/L1Portability/L1PortabilityTest$(LIBEXT)
LIBRARIES_STATIC+=$(BUILD_DIR)/L2Objects/L2ObjectsTest$(LIBEXT)
LIBRARIES_STATIC+=$(BUILD_DIR)/L3Streams/L3StreamsTest$(LIBEXT)
LIBRARIES_STATIC+=$(BUILD_DIR)/L4Configuration/L4ConfigurationTest$(LIBEXT)

OPTIM= -G6 -O2 -Ob2



